services:
  - type: web
    name: casamiento-katherine-ariel
    env: python
    buildCommand: "pip install -r requirements.txt && python database.py"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
